### ISSUE TITLE
You must enable the intl extension to use CakePHP

### ISSUE THREAD

**Issue by sumitkanoje** [GoogleCloudPlatform/appengine-cakephp-starter-app#4]
Getting this error.

`Fatal error:` You must enable the intl extension to use CakePHP. in `C:\~\app-engine\config\bootstrap.php on line 38`

**Comment by marslangoog** [comment]
Have you tried adding this line to your php.ini file?

extension="php_intl.dll"

**Comment by aig-morocco** [comment]
+1 @marslangoog That's how I solved it (Made me lose a couple of hours)

**Comment by sumitkanoje** [comment]
Yah..Even I did the same yesterday after looking at the logs in app-engine Log console.
Working fine.

**Comment by rohityadv876** [comment]
I have Enabled intl it shown INTL when I am running phpinfo() in the browser but cakephp does the same thing every time it.  You must enable the intl extension to use CakePHP.

I am using PHP 7.0, Latest version of xampp. I searched a lot to resolve this issue on stackoverflow. I did the same but getting the same error.

**Comment by marslangoog** [comment]
App Engine SDK for Windows is bundled with a specific version of PHP (PHP 5.5), you should use the launcher or dev_appserver.py to run your GAE project, not xampp or another other web server installed on your machine. See https://cloud.google.com/appengine/docs/php/tools/devserver for more details.

**Comment by tuutran47** [comment]
I have the same error. Everyone help?

**Comment by sumitkanoje** [comment]
Have you tried adding this line to your `php.ini` file?

`extension="php_intl.dll"`

**Comment by jigzat** [comment]
Same issue under iPage hosting. The PHP.INI has the extension line enabled. They havent figure out yet what's going on though might be a host issue.

**Comment by neethujj** [comment]
Fatal error: You must enable the intl extension to use CakePHP. in C:\xampp\htdocs\CakePHP1\cakephp-3-5-14\config\requirements.php on line 31
i cant fix with, extension="php_intl.dll"

**Comment by dectype** [comment]
The Cpanel now includes a graphic interface where you can install PHP extensions directly.

1. Login to your cPanel account.
2. Scroll down tht CPanel interface until you reach the Software and Service section
3. Click Select PHP Version
4. Find Intl extension, enable it and save.
Image URL : [https://url.dectype.com/intl-extension](url)

**Comment by dectype** [comment]
The Cpanel now includes a graphic interface where you can install PHP extensions directly.

1. Login to your cPanel account.
2. Scroll down tht CPanel interface until you reach the Software and Service section
3. Click Select PHP Version
4. Find Intl extension, enable it and save.
Image URL : http://url.dectype.com/intl-extension

**Comment by devsayanighosh** [comment]
Removed comment from the below line in php.ini file to resolve the fatal error:
extension=intl
CakePHP is running perfectly. Thanks for the help.

**Comment by thomsontochi** [comment]
extension="php_intl.dll" where do u add this?

**Comment by thatcyberguy** [comment]
> extension="php_intl.dll" where do u add this?

1- Open Xampp
2- From Apache, click on config
3- Double click php.ini
4- If you are on Windows Press Ctrl + f that will open a search box, and type intl
Note: Press up and Down to get more results from the search box

5- Locate that file ;extension=intl
6-remove the ;
7- and leave it like this   extension=intl

Save it and Happy Coding!!!

**Comment by hammas77** [comment]
i have the same issue , my extension=intl is enabled i removed the ; in front of it , saved the file and still getting this error 
Fatal error: You must enable the intl extension to use CakePHP. in C:\xampp\php\cakephp4\config\requirements.php on line 31
