### ISSUE TITLE
update the app skeleton to cakephp 3.3

### ISSUE THREAD

**Issue by alysson-azevedo** [GoogleCloudPlatform/appengine-cakephp-starter-app#6]
Hi. Since this project was created, cakephp updated from 3.0 to 3.3.

I'm doing some work to bring the updates from the cakephp' skeleton to this without losing the customizations that were done here. 

After i finish, should i make a pull-request?

**Comment by cyberbobjr** [comment]
Hi, 
necropost 👍 
maybe you can fork and publish your update :)

**Comment by alysson-azevedo** [comment]
Hi, dude. When I opened this thread, i was hoping to use gae to host the software i'm (still) developing.
But then I choose to host using another service.

So, lets close this issue for now. As you said, maybe sometime I can find time to update or even wait to cake4 be released.
